# Generated by Django 4.0.3 on 2022-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_developers_likes_developers_name_developers_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_text', models.TextField()),
            ],
        ),
    ]
